cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'cytopia/tap'
tap 'homebrew/binary'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/games'
tap 'homebrew/gui'
tap 'homebrew/science'
tap 'homebrew/versions'
tap 'homebrew/homebrew-php'
tap 'infinit/releases'
tap 'zyedidia/micro'
tap 'homebrew/bundle'
tap 'bramstein/webfonttools'

brew 'ack'
brew 'coreutils' # Install GNU core utilities (those that come with OS X are outdated) | https://www.gnu.org/software/coreutils
brew 'moreutils' # Install some other useful utilities like `sponge`. A collection of tools that nobody wrote when UNIX was young | https://joeyh.name/code/moreutils/
brew 'findutils' # Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed | https://www.gnu.org/software/findutils/
brew 'gnu-sed', args: ['with-default-names'] # Install GNU `sed`, overwriting the built-in `sed` | https://www.gnu.org/software/sed/
brew 'bash'
brew 'bash-completion2'
brew 'tmux'
brew 'ccat'
brew 'ranger'
brew 'micro'
brew 'doxygen'
brew 'mplayer'
brew 'python'
brew 'python3'
brew 'mplayer'
brew 'httpie'
brew 'hh'
brew 'noti'
brew 'openssl', args: ['universal']
brew 'cowsay'
brew 'curl'
# Install more recent versions of some OS X tools.
brew 'vim', args: ['override-system-vi']
brew 'homebrew/dupes/grep'
brew 'homebrew/dupes/openssh'
brew 'homebrew/dupes/screen'
brew 'php56', args: ['with-gmp']
# brew 'ruby' # Don't install ruby through brew, but with "rvm"
# Install font tools.
brew 'sfnt2woff'
brew 'sfnt2woff-zopfli'
brew 'woff2'
brew 'dark-mode'
brew 'git'
brew 'git-lfs'
brew 'go'
brew 'grc' # Colorize logfiles and command output | http://korpus.juls.savba.sk/~garabik/software/grc.html
brew 'imagemagick', args: ['with-webp', 'with-fontconfig']
brew 'ffmpeg', args: ['with-fontconfig', 'with-libass', 'with-faac']
brew 'lua'
brew 'lynx'
brew 'p7zip'
brew 'pigz'
brew 'pv'
brew 'michaeldfallen/formula/git-radar'
brew 'rename'
brew 'rhino'
brew 'speedtest_cli'
brew 'translate-shell'
brew 'ssh-copy-id'
brew 'tree'
brew 'webkit2png'
brew 'zopfli'
brew 'jp2a'
brew 'jq'
brew 'thefuck'
# brew 'node', args: ['without-npm'] Install by node install.sh
brew 'spark'
brew 'unrar'
brew 'wget', args: ['with-iri']
brew 'youtube-dl'
brew 'infinit/releases/infinit'

cask 'avast'
cask '1password'
cask 'android-studio'
cask 'android-file-transfer'
cask 'atom'
cask 'appcleaner'
cask 'basictex'
cask 'battle-net'
cask 'beardedspice'
cask 'bitbar'
cask 'color-oracle'
cask 'disk-inventory-x'
# cask 'disablemonitor'
cask 'docker'
cask 'dropbox'
cask 'ealeksandrov-cd-to'
cask 'firefox'
cask 'flux'
cask 'framer'
cask 'gfxcardstatus'
cask 'gitkraken'
cask 'gitter'
cask 'glueprint'
cask 'google-drive'
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'hyper'
cask 'infinit'
cask 'karabiner-elements'
cask 'keepingyouawake'
cask 'keycastr'
cask 'lumen'
cask 'mactex'
cask 'numi'
cask 'openemu'
cask 'opera-developer'
cask 'osxfuse'
cask 'rcdefaultapp'
cask 'simple-comic'
cask 'sketch'
cask 'sketch-toolbox'
cask 'skype'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'steam'
cask 'the-unarchiver'
cask 'torbrowser'
cask 'transmission'
cask 'vivaldi'
cask 'vlc'
cask 'xquartz'
cask 'wacom-intuos-pro-tablet'
cask 'wwdc'
cask 'zoomus'

## List of useful Quick Look plugins for developers | https://github.com/sindresorhus/quick-look-plugins
cask 'qlcolorcode'
cask 'qlstephen'
cask 'ttscoff-mmd-quicklook'
cask 'quicklook-json'
cask 'betterzipql'
cask 'qlimagesize'
cask 'suspicious-package'
cask 'quicklookase'
cask 'qlvideo'
cask 'quicklookapk'

brew 'diff-pdf'

## List of other applications
cask 'colorsnapper'
# cask 'istat-menus'
