alias remigrate='migrate' # Re-migratex a selected migration | Function in bin
alias migrategl='bin/rake db:migrate RAILS_ENV=development'
alias migrateglfull='bundle exec rake dev:setup RAILS_ENV=development'
#alias deldb="rm -rf ../postgresql/data && cd ../ && make" # Delete db and reconstruct it, be in gitlab folder of gdk
alias dbreset='rake db:drop db:create dev:setup'

alias kill3000='kill -9 $(lsof -i tcp:3000 -t)'
alias kill3001='kill -9 $(lsof -i tcp:3001 -t)'
alias kill3808='kill -9 $(lsof -i tcp:3808 -t)'

alias gpgitlab="git-push-gitlab"  # Creates new gitlab project from repository | Function in bin

alias glmr="git lab mr --checkout --id"

alias gltdone="gl-marktodosasdone" # Marks all todos with closed targets as done. Uses list generated by bitbar plugin | Funtion in bin